### ISSUE TITLE
Error following Getting Started

### ISSUE THREAD

**Issue by alexeypetrushin** [TrestleAdmin/trestle#6]
I followed the instruction in Getting Started guide, but when I go to http://localhost:3000/admin I get an error, see screenshot. 

```
undefined method `all' for nil:NilClass
```

<img width="745" alt="screen shot 2017-08-05 at 11 30 53 pm" src="https://user-images.githubusercontent.com/94196/28998550-6b3dc3d6-7a36-11e7-8af2-3c546add24c9.png">

**Comment by spohlenz** [comment]
It sounds like your model either doesn't exist or is not being correctly detected.

When you define an admin resource with `Trestle.resource(:posts)`, Trestle assumes that you have an existing model called `Post`. You can specify the model explicitly by passing it an option, i.e. `Trestle.resource(:posts, model: Article)`.

Having said that, I definitely need to add nicer error messages in this case.

**Comment by spohlenz** [comment]
A more appropriate exception and message has been introduced in fd8f9fd.

**Comment by alexeypetrushin** [comment]
Thank you! :)
